export type FeatureDetail = {
  title: string;
  description: string;
  image: any;
  Fee: number;
  duration: string;
  experience: string;
  rating: number;
  specialty: string;
};

export const featureDetails: Record<string, FeatureDetail> = {
  
  
  //Ent-Spelist
  'Dr. Rahul Mehta (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rahul Mehta',
    description: 'Dr. Rahul Mehta is a senior ENT specialist with over 10 years of experience. He excels in diagnosing and treating common issues like hearing loss, sore throat, nasal allergies, and chronic sinus infections. Known for his calm demeanor and effective consultation, he uses modern tools for accurate diagnosis and fast relief. His patients appreciate his personalized care and attention to detail, making him one of the most trusted ENT doctors in the region. He regularly updates his methods with the latest clinical research to ensure best outcomes for all age groups.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 550,
    duration: '15 mins',
    experience: '10 Years',
    rating: 5.0,
    specialty: 'ENT',
  },
  'Dr. Kavita Kapoor (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Kavita Kapoor',
    description: 'With 9 years of experience, Dr. Kavita Kapoor specializes in treating a variety of ENT conditions including throat infections, sinusitis, and chronic ear pain. She is well-regarded for her holistic treatment methods and empathetic approach towards patients. Her consultations are thorough, ensuring all underlying issues are addressed. Whether it’s a minor infection or recurring problem, Dr. Kavita provides effective care tailored to each individual. She regularly follows up with her patients to track recovery progress and adjust treatment accordingly.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 500,
    duration: '20 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'ENT',
  },
  'Dr. Vivek Chandra (⭐️⭐️⭐️)': {
    title: 'Dr. Vivek Chandra',
    description: 'Dr. Vivek Chandra is a skilled ENT surgeon with over 11 years of experience in complex surgeries and chronic ENT conditions. He is known for handling advanced procedures like nasal polyp removal, sinus surgeries, and ear reconstructions. While his rating reflects moderate patient wait times, his expertise is unmatched in surgical care. He focuses on long-term patient satisfaction, often educating them on post-surgery care and recovery. His surgical methods are backed by clinical research and technological advancements.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 600,
    duration: '25 mins',
    experience: '11 Years',
    rating: 3.0,
    specialty: 'ENT Surgery',
  },
  'Dr. Ananya Sood (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ananya Sood',
    description: 'An expert in ENT and allergy-related disorders, Dr. Ananya Sood helps patients manage conditions like nasal congestion, allergic rhinitis, and ENT-linked migraines. With 8 years of experience, she combines clinical expertise with a compassionate approach, focusing on patient comfort and long-term relief. Her accurate diagnosis and treatment planning make her a preferred choice for children and adults. She also guides patients on lifestyle changes to avoid allergy triggers and achieve sustained health.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 520,
    duration: '18 mins',
    experience: '8 Years',
    rating: 5.0,
    specialty: 'ENT & Allergy',
  },
  'Dr. Shubham Rathi (⭐️⭐️⭐️)': {
    title: 'Dr. Shubham Rathi',
    description: 'Dr. Shubham Rathi focuses on treating everyday ENT problems such as sore throat, ear infections, and nosebleeds. With 6 years of clinical practice, he uses the latest diagnostic tools to provide quick and effective relief. Although relatively younger in practice, he is praised for his polite behavior and clear communication. He ensures patients understand their condition before beginning any treatment. He offers follow-up support and home care tips to help with fast recovery.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 480,
    duration: '15 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'ENT Care',
  },
  'Dr. Isha Sharma (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Isha Sharma',
    description: 'Dr. Isha Sharma has 7 years of experience managing complex ENT issues such as voice disorders, nasal congestion, and chronic facial pain. She provides targeted treatments for vocal cord strain, nasal blockages, and ENT-related headaches. Known for her patient-friendly attitude and detailed explanations, she combines lifestyle advice with effective medical intervention. Her clinic is equipped with advanced ENT tools for accurate assessment. Patients often return for her reliable advice and consistent results.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 530,
    duration: '20 mins',
    experience: '7 Years',
    rating: 4.0,
    specialty: 'ENT Diagnosis',
  },
  'Dr. Mohit Verma (⭐️⭐️)': {
    title: 'Dr. Mohit Verma',
    description: 'Specializing in pediatric ENT care, Dr. Mohit Verma treats children with conditions like tonsillitis, adenoid problems, and ear infections. With 5 years of experience, he provides safe and gentle care tailored to younger patients. He ensures a friendly atmosphere to reduce anxiety among children. While still early in his career, he is appreciated by parents for his clear instructions, accessible communication, and consistent follow-ups. He promotes preventive care and early diagnosis in pediatric ENT health.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 490,
    duration: '15 mins',
    experience: '5 Years',
    rating: 2.0,
    specialty: 'Pediatric ENT',
  },
  'Dr. Ruchi Dey (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ruchi Dey',
    description: 'Dr. Ruchi Dey has 6 years of experience treating chronic sinus infections, nasal congestion, and headaches. She uses a mix of modern diagnostics and traditional care to provide relief. Her approach is centered on long-term management of ENT conditions with minimal discomfort. She also educates patients on dietary and environmental factors affecting their sinus health. Known for her punctual appointments and soft-spoken nature, Dr. Dey provides holistic ENT care that patients find highly dependable.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 500,
    duration: '18 mins',
    experience: '6 Years',
    rating: 4.0,
    specialty: 'Sinus & Nasal Care',
  },
  'Dr. Neeraj Mishra (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Neeraj Mishra',
    description: 'With 10 years of expertise, Dr. Neeraj Mishra specializes in treating snoring issues, sleep apnea, and voice-related problems. He offers advanced diagnosis and therapy for those with disturbed sleep and speech fatigue. His patients include professionals and senior citizens needing vocal health care. Dr. Mishra’s methods combine clinical treatment with practical lifestyle tips, ensuring better sleep and communication. He is especially known for personalized attention and using the latest tools in ENT sleep care.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 580,
    duration: '22 mins',
    experience: '10 Years',
    rating: 5.0,
    specialty: 'Sleep & Voice',
  },
  'Dr. Pooja Thakur (⭐️⭐️⭐️)': {
    title: 'Dr. Pooja Thakur',
    description: 'Dr. Pooja Thakur offers gentle and personalized care in treating throat pain, tonsillitis, and nasal congestion. With 7 years of experience, she caters to patients seeking effective yet simple treatments for recurring ENT issues. Her sessions are calm and informative, allowing patients to discuss concerns freely. She emphasizes early diagnosis and recovery, especially during weather-related allergies. Patients appreciate her respectful communication, availability for queries, and consistent monitoring for better health outcomes.',
    image: require('../assets/images/ENT Specialist.jpg'),
    Fee: 510,
    duration: '17 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Throat & Nose',
  },
  // Pediatricians
  'Dr. Meera Das (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Meera Das',
    description: 'Dr. Meera Das is a senior pediatrician with 9 years of experience in child healthcare and preventive medicine. She is trusted for managing childhood infections, regular health checkups, and nutritional guidance. Her clinic is well-equipped for infant vaccination and development monitoring. Known for her patient and friendly demeanor, she creates a comforting space for both kids and their parents. Dr. Meera also educates guardians on hygiene and immunity-building habits, ensuring healthy child growth from infancy to adolescence.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 550,
    duration: '20 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Child Health',
  },
  'Dr. Alok Rathi (⭐️⭐️)': {
    title: 'Dr. Alok Rathi',
    description: 'Dr. Alok Rathi has 5 years of pediatric experience focusing on fever management, seasonal illnesses, and basic child care. Though relatively new, he is appreciated for his soft-spoken approach and punctuality. He explains treatments clearly to anxious parents and provides digital prescriptions and follow-up options. His sessions often include guidance on hydration, nutrition, and preventive measures for toddlers and pre-schoolers. Suitable for basic illness diagnosis, general concerns, and first-time parent consultations.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 450,
    duration: '15 mins',
    experience: '5 Years',
    rating: 2.0,
    specialty: 'Child Illness',
  },
  'Dr. Sneha Khandelwal (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Sneha Khandelwal',
    description: 'Dr. Sneha Khandelwal specializes in pediatric nutrition, vaccination, and allergy care. With 8 years of experience, she provides reliable advice for newborn care, growth concerns, and childhood milestones. Parents value her calm communication style and practical parenting tips. She frequently advises on food habits, immunity boosters, and screen-time management. Her thorough assessments and detailed reports make her a trusted choice for parents seeking regular pediatric consultations in a stress-free environment.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 520,
    duration: '18 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Child Nutrition',
  },
  'Dr. Kunal Joshi (⭐️⭐️⭐️)': {
    title: 'Dr. Kunal Joshi',
    description: 'Dr. Kunal Joshi focuses on treating common pediatric conditions like cough, cold, stomach infections, and mild skin issues in children. With 6 years of experience, he provides care for children of all age groups. He is known for maintaining a balance between medication and natural recovery methods. Parents often prefer him for his clarity in communication and approachability. Dr. Joshi also offers guidance on sleep patterns and mental well-being in children.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 480,
    duration: '15 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'General Pediatrics',
  },
  'Dr. Riya Arora (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Riya Arora',
    description: 'With 10 years of pediatric expertise, Dr. Riya Arora is known for excellence in neonatal care, developmental delays, and vaccination programs. Her holistic consultation includes behavioral observations, milestone evaluations, and immunity plans. She has received recognition for her community outreach in child hygiene awareness. Parents trust her for her empathetic behavior and evidence-based treatment. She also encourages parents to maintain vaccination schedules and introduces eco-friendly hygiene routines for children.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 600,
    duration: '22 mins',
    experience: '10 Years',
    rating: 5.0,
    specialty: 'Neonatal & Development',
  },
  'Dr. Varun Yadav (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Varun Yadav',
    description: 'Dr. Varun Yadav offers 7 years of experience in pediatric emergencies, acute illnesses, and immunization. He responds calmly to urgent symptoms like high fever, dehydration, and allergic reactions. Parents admire his quick judgment and accurate treatment during stressful visits. He is equally skilled in routine check-ups and chronic condition management like asthma and anemia in kids. Dr. Varun integrates digital recordkeeping and sends regular vaccination alerts to ensure timely care.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 530,
    duration: '18 mins',
    experience: '7 Years',
    rating: 4.0,
    specialty: 'Pediatric Emergency',
  },
  'Dr. Priyanka Mehta (⭐️⭐️⭐️)': {
    title: 'Dr. Priyanka Mehta',
    description: 'Dr. Priyanka Mehta focuses on routine pediatric care including vaccinations, growth monitoring, and nutritional advice. With 6 years of experience, she simplifies complex medical terms for parents and ensures they feel comfortable asking questions. Her sessions involve practical parenting advice and follow-up routines. Though she handles mild to moderate issues, she is highly rated for her communication and empathy. She works well with first-time parents and infants up to 3 years old.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 490,
    duration: '16 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Vaccination & Wellness',
  },
  'Dr. Manish Kaul (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Manish Kaul',
    description: 'Dr. Manish Kaul is a highly experienced pediatrician with over 8 years in treating chronic childhood conditions, allergies, and behavioral issues. He emphasizes a scientific yet gentle approach to child psychology and development. His clinics offer hearing and speech screenings and ADHD management referrals. Parents trust him for long-term support and child progress tracking. He encourages minimal medication and often prescribes healthy lifestyle alternatives and structured daily routines for children.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 560,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Child Psychology & Allergy',
  },
  'Dr. Preeti Narang (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Preeti Narang',
    description: 'Dr. Preeti Narang is a pediatric expert with 11 years of experience in child health, immunization, and adolescent care. She is known for her detailed evaluations, regular health tracking, and mother-child counseling sessions. Her patients range from newborns to teenagers. She also promotes adolescent health education and is involved in school health programs. Parents respect her for empowering children with health awareness and managing emotional health along with physical wellness.',
    image: require('../assets/images/Pediatrician.jpg'),
    Fee: 610,
    duration: '25 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Adolescent & Preventive Care',
  },
  // Orthopedic Specialists
  'Dr. Rakesh Singh (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rakesh Singh',
    description: 'Dr. Rakesh Singh is an experienced orthopedic surgeon with 9 years of clinical practice in treating joint pain, arthritis, and bone injuries. He is skilled in both surgical and non-surgical methods and is known for patient-specific rehabilitation plans. His consultations include posture correction, mobility enhancement, and pain relief strategies. Dr. Singh is appreciated for clearly explaining X-rays and MRIs, making patients confident in their recovery journey. He also focuses on post-operative physiotherapy support and mobility guidance.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 580,
    duration: '20 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Joint & Bone Care',
  },
  'Dr. Aman Bansal (⭐️⭐️⭐️)': {
    title: 'Dr. Aman Bansal',
    description: 'With 6 years of experience, Dr. Aman Bansal treats sprains, fractures, and mild spine issues. His clinic is equipped with basic diagnostic and physiotherapy facilities. Though moderately rated, he is punctual and attentive to new patients. He helps patients manage pain through exercises, braces, and ergonomic tips. Ideal for non-critical bone and joint issues, Dr. Bansal is often recommended for minor sports injuries and age-related discomfort in knees and shoulders.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 480,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Fracture & Sports Injury',
  },
  'Dr. Supriya Narang (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Supriya Narang',
    description: 'Dr. Supriya Narang is a highly rated orthopedic specialist with 11 years of experience in joint replacement, back pain, and spinal alignment. She offers modern treatment for osteoporosis, scoliosis, and postural issues. Patients trust her for surgical precision, empathetic consultations, and recovery care. She promotes wellness through bone-strengthening diets and structured exercise routines. Dr. Narang frequently conducts bone health camps and educates the public about early signs of orthopedic conditions.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 640,
    duration: '25 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Spine & Joint Surgery',
  },
  'Dr. Hemant Sharma (⭐️⭐️)': {
    title: 'Dr. Hemant Sharma',
    description: 'Dr. Hemant Sharma provides orthopedic care with 4 years of experience, focusing on acute bone injuries, back pain, and muscle stiffness. While still early in his career, he is patient-friendly and offers practical advice for recovery at home. He helps manage sudden pain flare-ups and offers follow-up support digitally. Most suited for mild orthopedic complaints, he uses basic diagnostic tools and prefers conservative treatment unless absolutely necessary.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 420,
    duration: '15 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Muscle & Bone Injury',
  },
  'Dr. Kavya Rajput (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Kavya Rajput',
    description: 'Dr. Kavya Rajput brings 8 years of experience in orthopedic physiotherapy, joint inflammation treatment, and rehabilitation programs. She designs recovery plans for patients post-surgery or injury, particularly for knees, shoulders, and spine. She is praised for her personalized physiotherapy techniques, lifestyle recommendations, and regular tracking of progress. Her approach avoids surgery wherever possible and focuses on functional movement restoration.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 530,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Rehabilitation & Therapy',
  },
  'Dr. Nitin Deshmukh (⭐️⭐️⭐️)': {
    title: 'Dr. Nitin Deshmukh',
    description: 'Dr. Nitin Deshmukh has 6 years of experience handling work-related injuries, repetitive strain, and minor fractures. He promotes posture correction and ergonomic work habits. Ideal for office-goers and students suffering from neck or lower back pain, he offers simple and effective remedies. His patients find his diagnosis accurate and advice practical. He also provides exercise charts and back support recommendations for long-term relief.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 470,
    duration: '17 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Posture & Work Pain',
  },
  'Dr. Sameer Chauhan (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Sameer Chauhan',
    description: 'With 9 years of orthopedic expertise, Dr. Sameer Chauhan specializes in lower back disorders, disc bulges, and spinal realignment. He offers effective non-surgical interventions like traction therapy, posture improvement, and spinal exercises. His clinic has basic rehab equipment, and he coordinates with physiotherapists for comprehensive care. Patients rate him highly for long-term relief from back stiffness and posture correction.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 550,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Back Pain & Spine',
  },
  'Dr. Vaibhav Sinha (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Vaibhav Sinha',
    description: 'Dr. Vaibhav Sinha is an award-winning orthopedic surgeon with 12 years of experience in trauma care, joint replacements, and sports injuries. Known for his accurate surgical techniques and rapid recovery plans, he is a go-to for patients needing knee or hip surgery. He is also involved in orthopedic research and keeps his techniques updated. Patients trust him for his dedication, time-bound recovery timelines, and modern equipment use.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 700,
    duration: '28 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Joint Replacement',
  },
  'Dr. Renu Verma (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Renu Verma',
    description: 'Dr. Renu Verma offers orthopedic care with 7 years of experience in treating arthritis, frozen shoulder, and early joint degeneration. She adopts a conservative approach involving medication, physiotherapy, and lifestyle changes. Her patients value her detailed guidance on exercise routines, vitamin intake, and joint support. Dr. Verma is ideal for seniors or middle-aged patients seeking to avoid surgery and manage joint conditions naturally.',
    image: require('../assets/images/Orthopedic Specialist.jpg'),
    Fee: 520,
    duration: '19 mins',
    experience: '7 Years',
    rating: 4.0,
    specialty: 'Arthritis & Mobility',
  },
  // Gynecologists
  'Dr. Sanjana Gupta (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Sanjana Gupta',
    description: 'Dr. Sanjana Gupta is a senior gynecologist with 12 years of experience in managing high-risk pregnancies, PCOD, menstrual disorders, and infertility treatments. She is widely respected for her compassionate approach and advanced ultrasound diagnostics. Patients trust her for detailed consultation and treatment transparency. She also conducts workshops on women’s wellness, hormonal balance, and reproductive health. Her holistic care programs include nutrition advice and mental health support, making her a top choice for women across all age groups.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 650,
    duration: '25 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Pregnancy & PCOD',
  },
  'Dr. Neha Verma (⭐️⭐️⭐️)': {
    title: 'Dr. Neha Verma',
    description: 'With 7 years of gynecology experience, Dr. Neha Verma specializes in menstrual irregularities, pelvic pain, and contraception counseling. She is known for building strong rapport with young patients and explaining reproductive health with ease. Her consultations cover diet, stress, and hormonal triggers. Though mid-rated, she offers valuable care for common gynecological complaints and guides patients with both modern medication and natural lifestyle adjustments.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 500,
    duration: '18 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Menstrual Health',
  },
  'Dr. Anjali Sharma (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Anjali Sharma',
    description: 'Dr. Anjali Sharma brings 9 years of experience in women’s health, focusing on pregnancy care, PCOS management, and menopause support. She uses a combination of clinical tests, lifestyle guidance, and emotional counseling to support her patients. She is popular among expecting mothers for prenatal classes, breastfeeding guidance, and postnatal care. Her modern approach and strong follow-up system ensure comprehensive support throughout motherhood and beyond.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 580,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Prenatal & Menopause',
  },
  'Dr. Swati Patil (⭐️⭐️)': {
    title: 'Dr. Swati Patil',
    description: 'Dr. Swati Patil focuses on adolescent gynecology and basic reproductive health. With 4 years of practice, she handles common issues like cramps, infections, and puberty-related hormonal changes. Though rated modestly, she is known for being approachable and maintaining confidentiality. She educates teenage girls about menstrual hygiene and body changes, making her suitable for first-time consultations. Her clinic offers basic diagnostic facilities and affordable checkups.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 420,
    duration: '15 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Adolescent Care',
  },
  'Dr. Komal Mehra (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Komal Mehra',
    description: 'Dr. Komal Mehra is a leading gynecologist with 11 years of experience in IVF support, fertility preservation, and hormone therapy. She offers advanced treatments for PCOD, endometriosis, and irregular cycles. Her expertise in fertility helps couples conceive with clarity and confidence. She also provides counseling on sexual health and emotional well-being. Known for her empathetic listening, she maintains patient dignity and comfort throughout every consultation.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 670,
    duration: '26 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'IVF & Fertility',
  },
  'Dr. Rajni Tyagi (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rajni Tyagi',
    description: 'With 8 years of experience, Dr. Rajni Tyagi specializes in high-risk pregnancy and cesarean recovery care. She is known for her calm approach during delivery-related complications and provides extensive care to both mother and child. Her post-surgery follow-ups, diet charts, and emotional support build lasting trust among patients. Dr. Tyagi also hosts prenatal yoga sessions and childbirth education programs.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 610,
    duration: '23 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Pregnancy & Recovery',
  },
  'Dr. Shalini Dey (⭐️⭐️⭐️)': {
    title: 'Dr. Shalini Dey',
    description: 'Dr. Shalini Dey provides affordable gynecology consultations for common concerns such as UTI, itching, and hormonal acne. With 6 years of experience, she combines medication with home remedies to ease symptoms. Her strength lies in simplifying gyne-related knowledge for rural and urban patients alike. She is praised for being responsive on calls and offering telehealth support. Best suited for routine and initial check-ups.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 460,
    duration: '16 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Routine Gyne Care',
  },
  'Dr. Varsha Kaushik (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Varsha Kaushik',
    description: 'Dr. Varsha Kaushik is a well-known expert in managing PCOS, weight-linked fertility issues, and menstrual tracking. She advocates for natural remedies alongside clinical management. Her consultations include fitness advice, hormone analysis, and ovulation monitoring. With 8 years of experience, she is popular among women who prefer a balanced approach to hormonal issues. She also guides on anti-inflammatory diets and stress reduction methods.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 550,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'PCOS & Hormonal Health',
  },
  'Dr. Divya Sharma (⭐️⭐️⭐️)': {
    title: 'Dr. Divya Sharma',
    description: 'Dr. Divya Sharma is focused on period pain, thyroid-related cycle issues, and hormonal balance. With 6 years of experience, she builds rapport quickly and ensures patients feel heard and informed. She provides printed plans, regular follow-up reminders, and prescription guides. Ideal for working women dealing with lifestyle-related disruptions, she combines western and ayurvedic suggestions for symptom relief.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 480,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Cycle & Hormone Balance',
  },
  'Dr. Rekha Tiwari (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rekha Tiwari',
    description: 'With 13 years of experience, Dr. Rekha Tiwari is a senior gynecologist renowned for treating fibroids, cervical screening, and family planning. She promotes early screening for cervical cancer and offers empathetic advice on contraceptive options. Her in-depth sessions focus on emotional well-being and stress management for women across life stages. She is involved in national health programs and encourages regular wellness check-ups among working women.',
    image: require('../assets/images/Gynecologist.jpg'),
    Fee: 690,
    duration: '28 mins',
    experience: '13 Years',
    rating: 5.0,
    specialty: 'Women’s Wellness & Screening',
  },
   // General Physicians
  'Dr. Priya Jain (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Priya Jain',
    description: 'Dr. Priya Jain is a well-rounded general physician with 8 years of experience treating common conditions like fever, infections, digestive problems, and fatigue. Her consultation style is thorough, patient-centered, and focused on holistic recovery. She also specializes in seasonal illness care, routine blood work analysis, and lifestyle improvement plans. Patients appreciate her ability to explain diagnosis clearly and provide follow-up support via digital prescriptions and calls. She is a go-to for regular health maintenance and early diagnosis.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 480,
    duration: '18 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Common Illnesses',
  },
  'Dr. Ravi Kapoor (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ravi Kapoor',
    description: 'Dr. Ravi Kapoor has 9 years of experience in treating lifestyle-related illnesses like blood pressure, diabetes, and cholesterol imbalance. He encourages early diagnosis and long-term condition monitoring. His patients trust his data-driven approach to preventive health and fitness-based recovery. He often recommends diet and habit changes alongside medication. Dr. Kapoor is ideal for patients managing multiple mild conditions or preparing for routine medical checkups.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 500,
    duration: '20 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Lifestyle & Internal Medicine',
  },
  'Dr. Alisha Das (⭐️⭐️⭐️)': {
    title: 'Dr. Alisha Das',
    description: 'With 6 years of practice, Dr. Alisha Das treats infections, body aches, colds, and minor allergic reactions. She also helps with fatigue and digestion-related complaints. Her care focuses on comfort, quick medication-based relief, and simple home care suggestions. She’s known for being punctual and explaining treatment protocols in layman terms. Patients seek her help for early-stage symptoms and minor medical advice before specialist visits.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 450,
    duration: '16 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Basic Checkups',
  },
  'Dr. Rohan Seth (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rohan Seth',
    description: 'Dr. Rohan Seth is a senior general physician with 12 years of experience treating viral illnesses, chronic fatigue, immunity issues, and adult wellness. He has a structured and tech-driven approach to patient follow-up. Known for accurate diagnosis and lifestyle planning, he blends clinical judgment with personalized health advice. Dr. Seth regularly delivers health awareness sessions and is preferred for elderly care and adult preventive screening. Patients appreciate his calm nature and structured consultations.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 620,
    duration: '25 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Adult Wellness & Immunity',
  },
  'Dr. Monica Pillai (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Monica Pillai',
    description: 'Dr. Monica Pillai offers care for fevers, body weakness, allergies, and seasonal viral outbreaks. With 8 years of clinical experience, she is appreciated for her friendly consultations and detail-oriented treatment plans. She often advises young professionals on sleep, hydration, and nutrition. Dr. Pillai uses a digital health tracker for follow-ups and medication reminders. She is suitable for managing day-to-day illnesses in a fast-paced routine.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 510,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Viral & Routine Care',
  },
  'Dr. Tarun Rathi (⭐️⭐️⭐️)': {
    title: 'Dr. Tarun Rathi',
    description: 'Dr. Tarun Rathi has 5 years of experience treating common conditions such as cold, fever, mild infections, and indigestion. He’s known for being approachable and polite. His consultations focus on early treatment with minimal tests. While not specialized in chronic care, he handles one-time illnesses and minor recovery follow-ups efficiently. He provides both physical and telehealth services and is a good choice for working individuals seeking convenience.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 430,
    duration: '15 mins',
    experience: '5 Years',
    rating: 3.0,
    specialty: 'Cold & Fever',
  },
  'Dr. Harshita Goyal (⭐️⭐️)': {
    title: 'Dr. Harshita Goyal',
    description: 'With 3 years of experience, Dr. Harshita Goyal offers basic health consultations for minor aches, tiredness, skin rashes, and infections. She provides gentle care and comfort to first-time patients. While still early in her career, she uses checklists and clear communication to make patients feel confident. Her strength lies in building trust and guiding patients to further specialized care if needed.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 400,
    duration: '14 mins',
    experience: '3 Years',
    rating: 2.0,
    specialty: 'Initial Consults',
  },
  'Dr. Karan Malhotra (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Karan Malhotra',
    description: 'Dr. Karan Malhotra is an experienced general physician with 9 years of service in diagnosing infections, managing low immunity, and treating recurring headaches and fatigue. His sessions involve lab reviews, hydration planning, and fitness advice. He is a popular option for working adults, students, and middle-aged patients. His calm and data-backed treatment ensures clarity and compliance from patients.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 540,
    duration: '21 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Fatigue & Immunity',
  },
  'Dr. Jyoti Rawat (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Jyoti Rawat',
    description: 'Dr. Jyoti Rawat is a highly rated general physician with 11 years of experience in preventive health, stress-related illnesses, and family consultations. She offers detailed health reports and structured follow-up plans for working professionals and senior citizens. Her empathetic nature, prescription clarity, and health awareness advice are well recognized. She regularly offers webinars on healthy living and medical checkup schedules.',
    image: require('../assets/images/General Physician.jpg'),
    Fee: 600,
    duration: '24 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Family & Preventive Care',
  },
  
  // Dermatologists
  'Dr. Sneha Roy (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Sneha Roy',
    description: 'Dr. Sneha Roy is a skin care specialist with 8 years of experience in treating acne, pigmentation, and dull skin. She is known for her balanced approach using clinical treatments and home-care routines. Patients appreciate her skin analysis sessions, clear product suggestions, and seasonal skin maintenance tips. She’s a preferred choice among young adults and teens dealing with recurring breakouts and skin sensitivity. Her clinic offers chemical peels and acne scar treatments.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 520,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Acne & Pigmentation',
  },
  'Dr. Nikhil Mathur (⭐️⭐️)': {
    title: 'Dr. Nikhil Mathur',
    description: 'Dr. Nikhil Mathur treats mild skin conditions like rashes, itching, and scalp infections. With 4 years of experience, he focuses on first-line dermatology care using cost-effective methods. Though modestly rated, he is known for short wait times and easy appointment availability. He is best suited for common skin issues that require basic creams, antihistamines, and lifestyle suggestions.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 400,
    duration: '15 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Rashes & Allergies',
  },
  'Dr. Ritu Bansal (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ritu Bansal',
    description: 'Dr. Ritu Bansal is a top-rated dermatologist with 12 years of experience in treating acne scars, hair thinning, and aging skin. She uses advanced lasers, PRP, and chemical procedures for aesthetic results. Her treatment plans are structured and personalized, attracting both young clients and adults. She is also known for guiding patients on sunscreen use, hydration, and stress management for better skin outcomes.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 650,
    duration: '25 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Hair & Skin Aesthetics',
  },
  'Dr. Kanishka Dutt (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Kanishka Dutt',
    description: 'With 9 years of clinical experience, Dr. Kanishka Dutt specializes in treating fungal infections, hair fall, and skin allergies. She also handles skin hygiene-related concerns in teenagers and athletes. Her patients like her clarity, non-invasive plans, and hygiene-based tips. Her consultations include scalp health evaluations and skin hydration tracking.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 540,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Fungal & Hair Fall',
  },
  'Dr. Tanya Bakshi (⭐️⭐️⭐️)': {
    title: 'Dr. Tanya Bakshi',
    description: 'Dr. Tanya Bakshi has 6 years of experience in addressing dry skin, sun damage, and acne marks. She uses a mix of topical care, diet changes, and preventive routines to improve skin condition. Patients prefer her for quick skin consults and routine follow-ups. She is ideal for patients looking for day-to-day skincare advice and prevention of environmental skin damage.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 460,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Dry Skin & Sun Damage',
  },
  'Dr. Aryan Raj (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Aryan Raj',
    description: 'Dr. Aryan Raj is a renowned dermatologist with 11 years of experience in cosmetic dermatology, acne management, and skin rejuvenation. He offers laser therapy, microdermabrasion, and advanced facials for aesthetic enhancement. His clinic is equipped with the latest tools, and he regularly educates patients on proper skincare product usage. He’s a trusted name among working professionals and influencers.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 670,
    duration: '27 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Cosmetic Dermatology',
  },
  'Dr. Smita Sinha (⭐️⭐️⭐️)': {
    title: 'Dr. Smita Sinha',
    description: 'Dr. Smita Sinha helps with oily skin, scalp dandruff, and acne breakouts. With 7 years of experience, she builds care routines focused on product compatibility, stress control, and nighttime rituals. Patients rely on her for moderate skincare concerns and long-term oil control plans. Her consults include diet reviews and customized skin cleansing charts.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 470,
    duration: '19 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Oily Skin & Dandruff',
  },
  'Dr. Ekta Rawal (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ekta Rawal',
    description: 'Dr. Ekta Rawal offers comprehensive treatment for pigmentation, under-eye circles, and stress-induced skin problems. With 8 years of dermatology experience, she blends wellness coaching with prescription care. Patients feel confident under her guidance due to her gentle approach and clear skincare maps. She is especially preferred for facial glow improvement and skin tone balance.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 550,
    duration: '22 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Glow & Pigmentation',
  },
  'Dr. Rohit Anand (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rohit Anand',
    description: 'Dr. Rohit Anand is a senior dermatologist with 13 years of experience in psoriasis, eczema, and chronic skin conditions. He is known for detailed diagnosis, minimal side-effect treatments, and long-term condition control. His clinic is equipped for skin biopsies and patch testing. He also conducts skin awareness drives and educates on avoiding skin triggers. Patients consult him for dependable results and chronic condition support.',
    image: require('../assets/images/Dermatologist.jpg'),
    Fee: 690,
    duration: '28 mins',
    experience: '13 Years',
    rating: 5.0,
    specialty: 'Chronic Skin Conditions',
  },

  // Cardiologists
  'Dr. Vivek Malhotra (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Vivek Malhotra',
    description: 'Dr. Vivek Malhotra is a skilled cardiologist with 9 years of experience managing hypertension, chest pain, and arrhythmia. He performs ECGs, stress tests, and advises on medication and diet changes to improve heart health. Patients admire his ability to explain heart conditions in simple terms and provide personalized care plans. He is ideal for middle-aged individuals managing early signs of heart trouble or post-COVID cardiac follow-up.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 620,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Hypertension & Arrhythmia',
  },
  'Dr. Rajiv Ahuja (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Rajiv Ahuja',
    description: 'Dr. Rajiv Ahuja is a senior interventional cardiologist with 13 years of experience in angioplasty, heart failure treatment, and complex ECG interpretations. Known for accurate diagnosis and calm patient handling, he is highly rated by cardiac patients across age groups. His clinic offers treadmill testing and 2D echo facilities. Dr. Ahuja is also an advocate of preventive heart care and conducts regular awareness sessions.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 750,
    duration: '28 mins',
    experience: '13 Years',
    rating: 5.0,
    specialty: 'Cardiac Procedures',
  },
  'Dr. Anshika Sen (⭐️⭐️⭐️)': {
    title: 'Dr. Anshika Sen',
    description: 'With 6 years of experience, Dr. Anshika Sen manages lifestyle-induced cardiac concerns such as cholesterol imbalance, anxiety-triggered palpitations, and borderline BP. She promotes walking therapy, balanced diets, and stress reduction for heart wellness. Patients prefer her for her compassionate approach and easy-to-follow advice. Ideal for those with early symptoms or family history of heart problems.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 520,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Preventive Cardiology',
  },
  'Dr. Devendra Rathi (⭐️⭐️)': {
    title: 'Dr. Devendra Rathi',
    description: 'Dr. Devendra Rathi is a junior cardiologist with 4 years of experience in basic cardiac care and initial ECG interpretations. He offers advice on BP control, palpitations, and fatigue. Patients with mild symptoms and no major history of cardiac issues consult him for lifestyle tips and diet charts. His friendly consultations are suited for young adults and students with irregular BP complaints.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 430,
    duration: '15 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'BP & Pulse Issues',
  },
  'Dr. Mitali Chopra (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Mitali Chopra',
    description: 'Dr. Mitali Chopra brings 8 years of expertise in treating patients with valve disorders, post-surgical care, and lifestyle cardiac management. Her approach blends medication with dietary and habit-based interventions. Patients rely on her for long-term follow-ups and cardiac fitness routines. She also coordinates care for diabetic heart patients, ensuring multi-disciplinary guidance.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 610,
    duration: '21 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Valve & Lifestyle Care',
  },
  'Dr. Ashok Bansal (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Ashok Bansal',
    description: 'Dr. Ashok Bansal is a top-rated heart surgeon with 15+ years in advanced cardiac procedures like bypass surgery, pacemaker fitting, and stent placements. Patients consult him for second opinions, major cardiac advice, and surgery planning. He is well-known for his surgical outcomes, comprehensive care, and time-bound recovery programs. His clinic offers full cardiac workups and recovery charts.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 880,
    duration: '30 mins',
    experience: '15 Years',
    rating: 5.0,
    specialty: 'Cardiac Surgery',
  },
  'Dr. Shivani Nair (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Shivani Nair',
    description: 'Dr. Shivani Nair focuses on women’s heart health, cholesterol management, and stress-induced cardiac care. With 9 years of experience, she provides structured lifestyle assessments and works closely with dietitians and psychologists. Her sessions include heart health screenings and lifestyle scorecards. Patients appreciate her inclusive approach and practical advice for long-term well-being.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 600,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Women’s Cardiology',
  },
  'Dr. Nilesh Kulkarni (⭐️⭐️⭐️)': {
    title: 'Dr. Nilesh Kulkarni',
    description: 'With 7 years of experience, Dr. Nilesh Kulkarni handles heart palpitations, minor ECG abnormalities, and basic cardiac screenings. He is known for his soft-spoken behavior and willingness to spend time on patient questions. His advice focuses on stress reduction, activity moderation, and dietary shifts. Patients with mild irregularities or recent test concerns prefer his balanced consultation.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 490,
    duration: '18 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Basic Cardiac Care',
  },
  'Dr. Vikas Sethi (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Vikas Sethi',
    description: 'Dr. Vikas Sethi is a veteran cardiologist with 14 years of experience in advanced cardiac diagnostics, emergency care, and chronic heart disease management. He leads a heart wellness program that includes lab screenings, medication compliance, and family education. Patients praise his prompt diagnosis and commitment to patient education. He is often consulted for long-term management of cardiac conditions and hospital tie-up services.',
    image: require('../assets/images/Cardiologist.jpg'),
    Fee: 770,
    duration: '26 mins',
    experience: '14 Years',
    rating: 5.0,
    specialty: 'Chronic Cardiology',
  },

  // Psychiatrists
  'Dr. Shruti Sharma (⭐️⭐️⭐️)': {
    title: 'Dr. Shruti Sharma',
    description: 'Dr. Shruti Sharma is a compassionate psychiatrist with 6 years of experience treating anxiety, insomnia, and stress-related conditions. She uses a mix of cognitive therapy and medication to help patients cope with modern lifestyle issues. Known for her empathetic listening and calm demeanor, she works with young professionals and college students facing high-pressure environments. Her sessions also include stress tracking and relaxation techniques.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 500,
    duration: '20 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Anxiety & Insomnia',
  },
  'Dr. Aditya Khanna (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Aditya Khanna',
    description: 'Dr. Aditya Khanna has 9 years of experience treating mood disorders, panic attacks, and emotional regulation problems. He combines psychotherapy, medication, and behavior analysis to create holistic treatment plans. Patients find him approachable and clear in communication. He is preferred for both online and in-clinic counseling and offers lifestyle restructuring advice as part of his healing approach.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 580,
    duration: '22 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Mood & Panic Disorders',
  },
  'Dr. Tanya Grover (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Tanya Grover',
    description: 'Dr. Tanya Grover is a clinical psychiatrist with 8 years of experience specializing in women’s mental health, relationship challenges, and hormonal mood swings. Her therapy focuses on emotional healing, stress resilience, and improved communication. Patients appreciate her supportive counseling style and regular mental wellness check-ins. She also offers pre-marital and postpartum counseling.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 550,
    duration: '21 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Women’s Mental Health',
  },
  'Dr. Raghav Mittal (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Raghav Mittal',
    description: 'Dr. Raghav Mittal is a senior psychiatrist with 12 years of experience in treating depression, schizophrenia, and bipolar disorder. He is known for accurate diagnoses, compassionate support, and long-term care plans. He provides hospital tie-ups for severe psychiatric cases and is well-regarded in the field for professional ethics and confidentiality. His clinic has facilities for supervised medication and emergency interventions.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 700,
    duration: '30 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Chronic Mental Illness',
  },
  'Dr. Snehal Dixit (⭐️⭐️)': {
    title: 'Dr. Snehal Dixit',
    description: 'With 4 years of experience, Dr. Snehal Dixit helps patients struggling with overthinking, procrastination, and work-related anxiety. Her consultations include practical guidance, motivational therapy, and journaling-based interventions. While early in her career, she is patient-friendly and suitable for first-time therapy seekers or school/college-age youth experiencing emotional difficulty.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 420,
    duration: '18 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Youth & Motivation Therapy',
  },
  'Dr. Karthik Iyer (⭐️⭐️⭐️)': {
    title: 'Dr. Karthik Iyer',
    description: 'Dr. Karthik Iyer is a behavioral psychiatrist with 7 years of experience treating OCD, behavioral outbursts, and social phobia. His methods include habit reversal, exposure therapy, and CBT. He also works with families to resolve communication gaps and tension. He is ideal for patients struggling with compulsive behaviors and adjustment issues.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 490,
    duration: '19 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Behavioral Psychiatry',
  },
  'Dr. Mehul Shroff (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Mehul Shroff',
    description: 'Dr. Mehul Shroff offers psychiatric help for sleep disturbances, emotional burnout, and workplace trauma. With 10 years of experience, he integrates lifestyle mapping and medication for long-term healing. His sessions include progressive relaxation, emotional awareness activities, and guided breathing. Patients report improved rest patterns and emotional clarity.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 600,
    duration: '23 mins',
    experience: '10 Years',
    rating: 4.0,
    specialty: 'Sleep & Work Stress',
  },
  'Dr. Natasha Sehgal (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Natasha Sehgal',
    description: 'Dr. Natasha Sehgal is a highly rated psychiatrist with 11 years of experience in trauma recovery, PTSD care, and emotional stability therapy. She is appreciated for deep listening, personalized affirmations, and follow-up planning. Her clients include trauma survivors and professionals dealing with burnout or emotional numbness. She also provides group counseling and trauma journaling workshops.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 680,
    duration: '27 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Trauma & PTSD',
  },
  'Dr. Aditi Bansal (⭐️⭐️⭐️)': {
    title: 'Dr. Aditi Bansal',
    description: 'Dr. Aditi Bansal provides support for exam stress, social anxiety, and peer pressure. With 6 years of practice, she tailors mental wellness plans that include CBT, thought-challenging exercises, and self-esteem building. Her sessions help students and young adults navigate life transitions with clarity and confidence.',
    image: require('../assets/images/Psychiatrist.jpg'),
    Fee: 480,
    duration: '20 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Student Mental Health',
  },
  // Covid-19 Specialists
  'Dr. Arjun Sethi (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Arjun Sethi',
    description: 'Dr. Arjun Sethi is a dedicated Covid-19 specialist with 9 years of experience in managing viral infections and respiratory symptoms. He offers symptom screening, RT-PCR referrals, and recovery tracking for mild to moderate Covid cases. Patients prefer him for his reassuring consultation style, advice on isolation protocols, and immunity-boosting strategies. He also supports post-Covid care including breathing exercises and fatigue management.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 520,
    duration: '20 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Covid Diagnosis & Care',
  },
  'Dr. Manisha Rathi (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Manisha Rathi',
    description: 'Dr. Manisha Rathi is a senior pulmonologist and Covid expert with 12 years of experience in managing severe respiratory cases and hospital protocols. She consults on oxygen support, steroid therapy, and inflammation control. Her patients appreciate her timely decisions, recovery tracking, and preventive counseling. Dr. Rathi also advises high-risk individuals on pre-exposure precautions and immune support.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 700,
    duration: '25 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Severe Covid & Lung Care',
  },
  'Dr. Deepak Tiwari (⭐️⭐️⭐️)': {
    title: 'Dr. Deepak Tiwari',
    description: 'With 6 years of experience, Dr. Deepak Tiwari handles early-stage Covid symptoms like fever, cough, and loss of smell. He provides guidance on testing, isolation, and hydration therapy. His friendly nature makes him suitable for first-time patients and families monitoring mild symptoms at home. He also gives nutritional advice for immune support.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 450,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Mild Covid Care',
  },
  'Dr. Rekha Chopra (⭐️⭐️)': {
    title: 'Dr. Rekha Chopra',
    description: 'Dr. Rekha Chopra is a general physician with 4 years of experience providing Covid-related support like home isolation monitoring, fever control, and mental wellness during recovery. Her approach is patient-centric and she assists with recovery tracking, symptom progression, and post-Covid weakness. Ideal for stable patients needing home recovery help.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 400,
    duration: '15 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Home Isolation Guidance',
  },
  'Dr. Amaan Khan (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Amaan Khan',
    description: 'Dr. Amaan Khan has 8 years of experience in respiratory care and viral diagnostics. He treats patients with mild to moderate Covid symptoms and provides guidance on medicine schedules, hydration, and monitoring. He helps patients track their oxygen levels and pulse rate remotely. Patients value his calm advice during isolation and virtual follow-ups.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 520,
    duration: '20 mins',
    experience: '8 Years',
    rating: 4.0,
    specialty: 'Covid Monitoring',
  },
  'Dr. Sonali Saxena (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Sonali Saxena',
    description: 'Dr. Sonali Saxena is a Covid recovery expert with 11 years of experience in managing respiratory rehabilitation, long-Covid symptoms, and immune recovery. She offers counseling for fatigue, brain fog, and post-viral depression. Her programs include breathing therapy, diet charts, and follow-up routines. Her patients often consult her after hospital discharge for complete healing.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 640,
    duration: '24 mins',
    experience: '11 Years',
    rating: 5.0,
    specialty: 'Post-Covid Recovery',
  },
  'Dr. Yogesh Malviya (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Yogesh Malviya',
    description: 'Dr. Yogesh Malviya specializes in chest congestion, fever cycles, and symptom observation during Covid infection. With 7 years of experience, he provides isolation strategies, medicine recommendations, and hygiene protocols. Patients prefer his structured video consults and timely prescriptions. He also follows up for reinfection cases and testing schedules.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 510,
    duration: '19 mins',
    experience: '7 Years',
    rating: 4.0,
    specialty: 'Covid Symptoms & Safety',
  },
  'Dr. Seema Pandey (⭐️⭐️⭐️)': {
    title: 'Dr. Seema Pandey',
    description: 'Dr. Seema Pandey offers basic Covid consultation for symptom clarification, medication overview, and dietary guidance. With 5 years of practice, she is ideal for mild symptom cases, travel-related exposure, or Covid testing concerns. Patients find her practical, responsive, and suitable for remote health checks during isolation.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 460,
    duration: '17 mins',
    experience: '5 Years',
    rating: 3.0,
    specialty: 'General Covid Support',
  },
  'Dr. Vishal Rana (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Vishal Rana',
    description: 'Dr. Vishal Rana is a leading Covid care consultant with 13 years of experience in infectious disease management. He leads isolation care protocols, monitors high-risk individuals, and educates families on preventing spread. Patients appreciate his detailed plans, virtual supervision, and holistic recovery approach. He also provides vaccination counseling and immunity programs.',
    image: require('../assets/images/Covid-19 Specialist.jpg'),
    Fee: 720,
    duration: '26 mins',
    experience: '13 Years',
    rating: 5.0,
    specialty: 'Infectious Disease & Covid Care',
  },
  // Emergency Care
  'Dr. Suresh Iyer (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Suresh Iyer',
    description: 'Dr. Suresh Iyer is a senior emergency care specialist with 11 years of experience handling trauma cases, accidents, and critical medical events. His expertise includes airway management, trauma stabilization, and early intervention for stroke and cardiac arrest. Patients trust his calm demeanor and quick decision-making in high-pressure situations. He also trains paramedics and contributes to emergency protocol development.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 700,
    duration: '20 mins',
    experience: '11 Years',
    rating: 4.0,
    specialty: 'Emergency Trauma Care',
  },
  'Dr. Pallavi Rao (⭐️⭐️⭐️)': {
    title: 'Dr. Pallavi Rao',
    description: 'Dr. Pallavi Rao is an emergency response physician with 6 years of experience managing minor trauma, allergic reactions, and acute injuries. She ensures rapid triage, wound care, and initial stabilization. She is appreciated for her clear communication and quick treatment of walk-in patients. Suitable for minor emergencies, she also provides instructions for home monitoring after first aid.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 500,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Minor Injury & First Aid',
  },
  'Dr. Faizan Khan (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Faizan Khan',
    description: 'Dr. Faizan Khan is a critical care expert with 13 years of experience in managing ICU admissions, head trauma, and cardiac emergencies. He is known for quick assessments, ventilator management, and CPR coordination. His leadership in emergency rooms is admired for precision and timely action. He also helps design city-level emergency response strategies and ambulance tie-ups.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 780,
    duration: '25 mins',
    experience: '13 Years',
    rating: 5.0,
    specialty: 'ICU & Cardiac Emergency',
  },
  'Dr. Ruchi Sharma (⭐️⭐️)': {
    title: 'Dr. Ruchi Sharma',
    description: 'Dr. Ruchi Sharma offers basic emergency consultation and first-line care for dizziness, minor burns, and trauma shock symptoms. With 4 years of practice, she is patient-friendly and handles outpatient emergencies efficiently. She provides clear post-emergency advice and is often consulted for second opinions on ER reports and scans.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 420,
    duration: '16 mins',
    experience: '4 Years',
    rating: 2.0,
    specialty: 'Primary Emergency Aid',
  },
  'Dr. Alok Taneja (⭐️⭐️⭐️)': {
    title: 'Dr. Alok Taneja',
    description: 'Dr. Alok Taneja is experienced in managing road accidents, fractures, and deep wound stabilization. With 7 years in emergency departments, he is skilled in managing trauma patients and coordinating with surgeons. He is known for reducing patient wait time and initiating pain management quickly. He also contributes to hospital emergency drills and training.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 520,
    duration: '19 mins',
    experience: '7 Years',
    rating: 3.0,
    specialty: 'Accident Response',
  },
  'Dr. Meera Vyas (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Meera Vyas',
    description: 'Dr. Meera Vyas is a responsive ER consultant with 9 years of experience in trauma, poisoning, and critical fever cases. She is praised for her structured approach and coordination with ICU teams. She provides post-discharge counseling and also supports family members in understanding critical care needs and steps.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 600,
    duration: '21 mins',
    experience: '9 Years',
    rating: 4.0,
    specialty: 'Emergency Coordination',
  },
  'Dr. Danish Qureshi (⭐️⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Danish Qureshi',
    description: 'Dr. Danish Qureshi has over 12 years of experience handling complex emergencies including seizures, multi-organ shock, and respiratory arrest. He is equipped with advanced critical care training and works closely with ambulance and paramedic services. Dr. Qureshi is trusted for his proactive triage system and accurate emergency diagnosis. He also helps design hospital-level ER protocols.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 760,
    duration: '24 mins',
    experience: '12 Years',
    rating: 5.0,
    specialty: 'Advanced Critical Care',
  },
  'Dr. Simran Kohli (⭐️⭐️⭐️)': {
    title: 'Dr. Simran Kohli',
    description: 'With 6 years of practice, Dr. Simran Kohli provides quick emergency intervention for dehydration, high fever, and fainting spells. She is known for her soft-spoken nature and supportive guidance. She ensures timely assessment and follows up with home care instructions post-emergency. Ideal for parents, seniors, or students dealing with non-life-threatening but urgent conditions.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 500,
    duration: '18 mins',
    experience: '6 Years',
    rating: 3.0,
    specialty: 'Basic Urgent Care',
  },
  'Dr. Vikram Pal (⭐️⭐️⭐️⭐️)': {
    title: 'Dr. Vikram Pal',
    description: 'Dr. Vikram Pal is a trauma response specialist with 10 years of experience in managing bleeding injuries, unconscious episodes, and head injuries. He is trained in trauma protocols and rapid decision-making under pressure. He assists in emergency room automation and has helped streamline ER workflows in multispecialty hospitals.',
    image: require('../assets/images/Emergency Care.jpg'),
    Fee: 680,
    duration: '22 mins',
    experience: '10 Years',
    rating: 4.0,
    specialty: 'Head & Trauma Emergencies',
  }

};











